# ==============================================================
# =  API GATEWAYY
# ==============================================================

server.port=8081
spring.application.name=api-gatewayy

# ============= EUREKA CLIENT CONFIGURATION =========

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.discovery.locator.enabled=false